#! /bin/bash
#
#  \Author Hans Kramer
#
#  \Date   March 2018
#
#  \Code   Krrrrrrazy color prompt
#
#  \Usage  source kcp_fire
#

export kcp_segment_len=5
export kcp_color=0


function kcp_color_print() {
    case $kcp_color in 
    0)
        printf "\001\x1b[48;2;$1;$2;$2m\002$3"
	;;
    1)
        printf "\001\x1b[48;2;$2;$1;$2m\002$3"
	;;
    2)
        printf "\001\x1b[48;2;$2;$2;$1m\002$3"
	;;
    3)
        printf "\001\x1b[48;2;$1;$1;$2m\002$3"
	;;
    4)
        printf "\001\x1b[48;2;$1;$2;$1m\002$3"
	;;
    5)
        printf "\001\x1b[48;2;$2;$1;$1m\002$3"
	;;
    6)
        printf "\001\x1b[48;2;$1;$1;$1m\002$3"
	;;
    esac
}


function kcp() {
    if (( ${#1} < 3 )) ; then
	# not implemented yet
        return
    fi
    printf "\001\x1b[38;2;255;255;255m\002"

    (( sect_len = ${#1} / 3 ))
    (( sect_len = sect_len > $kcp_segment_len ? $kcp_segment_len : sect_len ))
   
    (( n_seg     = ${#1}/sect_len  ))
    (( s_seg     = n_seg/2         ))
    (( m_seg_len = ${#1}-s_seg*2*sect_len ))

    (( bg_highlight_next  = 0 ))
    (( c = s_seg*sect_len ))
    for (( i=0; c>0; i++,c-- )); do
	(( offset = $i % sect_len ))
	(( $i % sect_len )) || {
	    (( bg_highlight_start  = bg_highlight_next ))
            (( bg_highlight_next   = 55 + RANDOM % 200  ))
	}
	(( bg_highlight = (($bg_highlight_next-$bg_highlight_start)/(sect_len-1))*$offset + $bg_highlight_start ))
	kcp_color_print ${bg_highlight} 0 ${1:$i:1}
    done

    (( c = m_seg_len ))
    for (( ; c>0; i++,c-- )); do
	(( offset = $i % sect_len ))
	(( $i % sect_len )) || {
	    (( bg_highlight_start  = bg_highlight_next ))
            (( bg_highlight_next   = 55 + RANDOM % 200  ))
	}
        (( bg_highlight = (($bg_highlight_next-$bg_highlight_start)/sect_len)*$offset + $bg_highlight_start ))
	kcp_color_print ${bg_highlight} 0 ${1:$i:1}
    done
    (( c = s_seg*sect_len ))
    for (( offset=0; c>0; i++,c--,offset++ )); do
	(( offset = $offset % sect_len ))
	if (( $i > ${#1}-sect_len-1 )) ; then
	    (( bg_highlight_start  = bg_highlight_next ))
	    if (( $i+1 != ${#1} )) ; then
	        (( bg_other = 0 ))
	    else
	        (( bg_other = 35 ))
            fi
	    (( bg_highlight = ((35-$bg_highlight_start)/(sect_len-1))*$offset + $bg_highlight_start ))
	    kcp_color_print ${bg_highlight} ${bg_other} ${1:$i:1}
        else
            (( $c % sect_len )) || {
	        (( bg_highlight_start  = bg_highlight_next ))
                (( bg_highlight_next   = 55 + RANDOM % 200  ))
	    }
            (( bg_highlight = (($bg_highlight_next-$bg_highlight_start)/(sect_len-1))*$offset + $bg_highlight_start ))
	    kcp_color_print ${bg_highlight} 0 ${1:$i:1}
	fi
    done

    return
}

PS1='\[\033[01;31m\]$(kcp "[\u@\h \W]\$")\[\033[0m\] '
