#! /bin/bash
#
#  \Author Hans Kramer
#
#  \Date   March 2018
#
#  \Code   Krrrrrrazy color prompt
#
#  \Usage  source kcp_gray_bg
#

function kcp() {
    bg_mid=200
    bg_edge=35

    fg_red=0
    fg_green=0
    fg_blue_mid=255
    fg_blue_edge=100

    for (( i=0; i<${#1}; i++ )); do
        (( x = ${#1}/2 - $i )) 
        (( x = ${x#-} )) 
        (( bg = (${#1}/2 - $x)*($bg_mid-$bg_edge)/(${#1}/2) + $bg_edge ))
	(( fg_blue = (${#1}/2 - $x)*($fg_blue_mid-$fg_blue_edge)/(${#1}/2) + $fg_blue_edge ))
        printf "\001\x1b[48;2;${bg};${bg};${bg}m\x1b[38;2;${fg_red};${fg_green};${fg_blue}m\002${1:$i:1}"
    done
}

PS1='\[\033[01;31m\]$(kcp "[\u@\h \W]\$")\[\033[0m\] '
