#! /bin/bash
#
#  \Author Hans Kramer
#
#  \Date   March 2018
#
#  \Code   Krrrrrrazy color prompt
#
#  \Usage  source kcp
#

function kcp() {
    bg_start=200
    bg_end=40

    fg_red=0
    fg_green=0
    fg_blue_start=255
    fg_blue_end=0

    for (( i=0; i<${#1}; i++ )); do
	(( bg = $bg_start + $i*($bg_end-$bg_start)/${#1} ))
	(( fg_blue = $fg_blue_start + $i*($fg_blue_end-$fg_blue_start)/${#1} ))
        echo -ne "\001\x1b[48;2;${bg};${bg};${bg}m\x1b[38;2;${fg_red};${fg_green};${fg_blue}m\002${1:$i:1}"
    done
}

PS1='\[\033[01;31m\]$(kcp "[\u@\h \W]\$")\[\033[0m\] '
